# Generated by Django 6.0.3 on 2026-03-12 20:08

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.TextField(unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_candidate_id', models.IntegerField(blank=True, help_text='gestor_rh_vacante_candidato.id', null=True)),
                ('source_vacante_id', models.IntegerField(blank=True, help_text='gestor_rh_vacante.id', null=True)),
                ('processing_meta_json', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='gestor_rh_perfil_puesto.id', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_content', models.TextField(blank=True, default='')),
                ('full_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_type', models.CharField(choices=[('general', 'General'), ('summary', 'Resumen / Perfil'), ('experience', 'Experiencia'), ('education', 'Educación'), ('skills', 'Habilidades / Software'), ('languages', 'Idiomas'), ('certifications', 'Certificaciones / Capacitación')], default='general', max_length=30)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='hiring.candidatedocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='cand_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_candidate_chunk_document_index')],
            },
        ),
        migrations.CreateModel(
            name='JobProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('education', 'Educación'), ('experience', 'Experiencia'), ('skills', 'Skills / Software'), ('languages', 'Idiomas'), ('certifications', 'Capacitación'), ('general', 'General / Adicionales')], max_length=30)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hiring.jobprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_profile', 'section_type'), name='uniq_job_profile_section_type')],
            },
        ),
    ]
