# Generated by Django 6.0.3 on 2026-03-18 21:42

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='gestor_rh_vacante.id', unique=True)),
                ('profile_name', models.CharField(help_text='Nombre del perfil de puesto asociado', max_length=255)),
                ('profile_source_id', models.IntegerField(blank=True, help_text='gestor_rh_perfil_puesto.id', null=True)),
                ('tipo_vacante', models.CharField(blank=True, default='', max_length=50)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('sucursal_id', models.IntegerField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('full_content', models.TextField(blank=True, default='')),
                ('full_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('snapshot_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='VacancySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('education', 'Educación'), ('experience', 'Experiencia'), ('skills', 'Skills / Software'), ('languages', 'Idiomas'), ('certifications', 'Capacitación'), ('general', 'General / Adicionales')], max_length=30)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='jobprofilesection',
            name='uniq_job_profile_section_type',
        ),
        migrations.AddField(
            model_name='vacancysection',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hiring.vacancy'),
        ),
        migrations.RemoveField(
            model_name='jobprofilesection',
            name='job_profile',
        ),
        migrations.AddConstraint(
            model_name='vacancysection',
            constraint=models.UniqueConstraint(fields=('vacancy', 'section_type'), name='uniq_vacancy_section_type'),
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='JobProfileSection',
        ),
    ]
