# Generated by Django 6.0.3 on 2026-03-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_vacancy_vacancysection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_source_id', models.IntegerField()),
                ('vacancy_name', models.CharField(max_length=255)),
                ('candidates_evaluated', models.IntegerField(default=0)),
                ('top_score', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('weights_used', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='candidatedocument',
            name='sha256',
        ),
        migrations.CreateModel(
            name='MatchRunCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_candidate_id', models.IntegerField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField()),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('candidate_status_at_run', models.CharField(blank=True, default='', max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.candidatedocument')),
                ('match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hiring.matchrun')),
            ],
            options={
                'ordering': ['match_run', 'rank'],
            },
        ),
    ]
