# Generated by Django 6.0.3 on 2026-03-26 06:13

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_matchrun_remove_candidatedocument_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard_type', models.CharField(choices=[('text', 'Texto'), ('attribute', 'Atributo')], default='text', max_length=20)),
                ('eval_mode', models.CharField(choices=[('score', 'Puntuación'), ('filter', 'Filtro'), ('informational', 'Informativo')], default='score', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='Criterio en texto libre (tipo text)')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
                ('attribute_slug', models.CharField(blank=True, default='', help_text='Slug del atributo: stability, min_experience, min_education, cv_completeness', max_length=50)),
                ('attribute_config', models.JSONField(blank=True, default=dict, help_text='Config del atributo, ej: {min_level: media}, {min_years: 2}')),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
